image: Visual Studio 2022

environment:
  QT5: C:\Qt\5.15.2\msvc2019_64
  QT6: C:\Qt\6.5.0\msvc2019_64

install:
  - set PATH=%PATH%;%QT5%\bin

build: off

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH=%QT5% ..

build_script:
  - cmake --build . --config Release

after_build:
  - cd ..
  - mkdir release
  - copy build\Release\openck.exe release\
  - copy build\editor.ini release\

test_script:
  - cd release
  - openck.exe --version
