#ifndef COMPONENTRECORDTYPES_HPP
#define COMPONENTRECORDTYPES_HPP

// Every record struct that participates in the component architecture. The
// list is shared by the type-erased resolvers (formcomponentsresolver.cpp) and
// the paste path (recordpaste.cpp) so the two can never drift apart.
//
// Include the record headers for the listed types before using this macro.
#define FOR_EACH_COMPONENT_RECORD_TYPE(MACRO) \
    MACRO(AactRecord) \
    MACRO(AamdRecord) \
    MACRO(AapdRecord) \
    MACRO(AchrRecord) \
    MACRO(ActiRecord) \
    MACRO(ActorValueInfoRecord) \
    MACRO(AddnRecord) \
    MACRO(AffeRecord) \
    MACRO(AlchRecord) \
    MACRO(AmbsRecord) \
    MACRO(AmdlRecord) \
    MACRO(AmmoRecord) \
    MACRO(AnioRecord) \
    MACRO(AopfRecord) \
    MACRO(AopsRecord) \
    MACRO(AoruRecord) \
    MACRO(AppaRecord) \
    MACRO(ArmaRecord) \
    MACRO(ArmorRecord) \
    MACRO(ArtoRecord) \
    MACRO(ArtvRecord) \
    MACRO(AspcRecord) \
    MACRO(AtmoRecord) \
    MACRO(AvmdRecord) \
    MACRO(BiomRecord) \
    MACRO(BookRecord) \
    MACRO(BmmoRecord) \
    MACRO(BmodRecord) \
    MACRO(BndsRecord) \
    MACRO(BptdRecord) \
    MACRO(BsgnRecord) \
    MACRO(CamsRecord) \
    MACRO(CellRecord) \
    MACRO(ChalRecord) \
    MACRO(CldfRecord) \
    MACRO(ClassRecord) \
    MACRO(ClfmRecord) \
    MACRO(ClimateRecord) \
    MACRO(ClotRecord) \
    MACRO(CndfRecord) \
    MACRO(CobjRecord) \
    MACRO(CollRecord) \
    MACRO(ContRecord) \
    MACRO(CpthRecord) \
    MACRO(CreatureRecord) \
    MACRO(CstyRecord) \
    MACRO(DlbrRecord) \
    MACRO(Cur3Record) \
    MACRO(CurvRecord) \
    MACRO(DebrRecord) \
    MACRO(DfobRecord) \
    MACRO(DialRecord) \
    MACRO(DmgtRecord) \
    MACRO(DobjRecord) \
    MACRO(DoorRecord) \
    MACRO(EcznRecord) \
    MACRO(EfshRecord) \
    MACRO(EfsqRecord) \
    MACRO(EnchRecord) \
    MACRO(EqupRecord) \
    MACRO(ExplRecord) \
    MACRO(EyesRecord) \
    MACRO(FactRecord) \
    MACRO(FlorRecord) \
    MACRO(FormListRecord) \
    MACRO(FurnRecord) \
    MACRO(GrassRecord) \
    MACRO(HairRecord) \
    MACRO(HazdRecord) \
    MACRO(HdptRecord) \
    MACRO(IdleAnimationRecord) \
    MACRO(IdleMarkerRecord) \
    MACRO(ImgsRecord) \
    MACRO(InfoRecord) \
    MACRO(IngrRecord) \
    MACRO(IpctRecord) \
    MACRO(IpdsRecord) \
    MACRO(KeymRecord) \
    MACRO(KeywordRecord) \
    MACRO(LandRecord) \
    MACRO(LighRecord) \
    MACRO(LoadScreenRecord) \
    MACRO(LocationRecord) \
    MACRO(LtexRecord) \
    MACRO(LvlcRecord) \
    MACRO(LvliRecord) \
    MACRO(LvspRecord) \
    MACRO(MagicRecord) \
    MACRO(MaterialRecord) \
    MACRO(MattRecord) \
    MACRO(MovtRecord) \
    MACRO(MuscRecord) \
    MACRO(FfkwRecord) \
    MACRO(FogvRecord) \
    MACRO(ForcRecord) \
    MACRO(FstpRecord) \
    MACRO(FstsRecord) \
    MACRO(FxpdRecord) \
    MACRO(GbfmRecord) \
    MACRO(GbftRecord) \
    MACRO(GcvrRecord) \
    MACRO(ImadRecord) \
    MACRO(InnrRecord) \
    MACRO(IresRecord) \
    MACRO(KssmRecord) \
    MACRO(LayrRecord) \
    MACRO(LensRecord) \
    MACRO(LgdiRecord) \
    MACRO(LgtmRecord) \
    MACRO(LmswRecord) \
    MACRO(LvlbRecord) \
    MACRO(LvlnRecord) \
    MACRO(LvlpRecord) \
    MACRO(LvscRecord) \
    MACRO(MaamRecord) \
    MACRO(MrhpRecord) \
    MACRO(MtptRecord) \
    MACRO(NaviRecord) \
    MACRO(NocmRecord) \
    MACRO(OmodRecord) \
    MACRO(OswpRecord) \
    MACRO(OvisRecord) \
    MACRO(PcbnRecord) \
    MACRO(PccnRecord) \
    MACRO(PcmtRecord) \
    MACRO(PdclRecord) \
    MACRO(PgreRecord) \
    MACRO(MesgRecord) \
    MACRO(MiscRecord) \
    MACRO(MsttRecord) \
    MACRO(MustRecord) \
    MACRO(NavmRecord) \
    MACRO(NpcRecord) \
    MACRO(NoteRecord) \
    MACRO(OutfitRecord) \
    MACRO(PackageRecord) \
    MACRO(PerkRecord) \
    MACRO(PndRecord) \
    MACRO(ProjRecord) \
    MACRO(QuestRecord) \
    MACRO(RaceRecord) \
    MACRO(RefrRecord) \
    MACRO(RegionRecord) \
    MACRO(RelaRecord) \
    MACRO(RevbRecord) \
    MACRO(RoadRecord) \
    MACRO(ScriptRecord) \
    MACRO(ScrRecord) \
    MACRO(ShouRecord) \
    MACRO(SlgmRecord) \
    MACRO(SmqnRecord) \
    MACRO(SounRecord) \
    MACRO(SpellRecord) \
    MACRO(SpgdRecord) \
    MACRO(StaticCollectionRecord) \
    MACRO(StatRecord) \
    MACRO(ScenRecord) \
    MACRO(TermRecord) \
    MACRO(TextureSetRecord) \
    MACRO(TreeRecord) \
    MACRO(WateRecord) \
    MACRO(WeaponRecord) \
    MACRO(WorldspaceRecord) \
    MACRO(WthrRecord) \
    MACRO(PhzdRecord) \
    MACRO(PkinRecord) \
    MACRO(PmftRecord) \
    MACRO(PsdcRecord) \
    MACRO(PtstRecord) \
    MACRO(RfgpRecord) \
    MACRO(RsgdRecord) \
    MACRO(RspjRecord) \
    MACRO(SdltRecord) \
    MACRO(SechRecord) \
    MACRO(SfbkRecord) \
    MACRO(SfpcRecord) \
    MACRO(SfptRecord) \
    MACRO(SftrRecord) \
    MACRO(SmbnRecord) \
    MACRO(SmenRecord) \
    MACRO(SpchRecord) \
    MACRO(StagRecord) \
    MACRO(StbhRecord) \
    MACRO(StdtRecord) \
    MACRO(StmpRecord) \
    MACRO(StndRecord) \
    MACRO(SunpRecord) \
    MACRO(TmlmRecord) \
    MACRO(ToddRecord) \
    MACRO(TravRecord) \
    MACRO(TrnsRecord) \
    MACRO(VoliRecord) \
    MACRO(VtypRecord) \
    MACRO(WbarRecord) \
    MACRO(WkmfRecord) \
    MACRO(WthsRecord) \
    MACRO(WwedRecord) \
    MACRO(Tes3Record) \
    MACRO(ZoomRecord)

#endif // COMPONENTRECORDTYPES_HPP
